name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECT_CLIENT_WORKSPACE: './src/cv-client'
  DOTNET_VERSION: 7.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  VERBOSITY: normal

jobs:
  build_iac:
    name: Build (IaC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test projects
        uses: amilochau/github-actions/build/terraform@v3
   
  build_client:
    name: Build (Client)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: "${{ env.PROJECT_CLIENT_WORKSPACE }}/package-lock.json"
      - name: Install packages
        shell: pwsh
        run: npm ci
        working-directory: ${{ env.PROJECT_CLIENT_WORKSPACE }}
      - name: Run linter
        shell: pwsh
        run: npm run lint
        working-directory: ${{ env.PROJECT_CLIENT_WORKSPACE }}
      - name: Build application
        shell: pwsh
        run: npm run build
        working-directory: ${{ env.PROJECT_CLIENT_WORKSPACE }}
