name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECT_CLIENT_WORKSPACE: './src/cv-client'

jobs:
  build_iac:
    name: Build (IaC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test projects
        uses: amilochau/github-actions/build/terraform@v4
   
  build_client:
    name: Build (Client)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        uses: amilochau/github-actions/build/node@v4
        with:
          projectWorkspace: ${{ env.PROJECT_CLIENT_WORKSPACE }}
