name: Deploy
run-name: Deploy - ${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
    - main

concurrency: deploy

env:
  INFRA_WORKSPACE_DEV: dev
  INFRA_WORKSPACE_PRD: prd
  INFRA_AWS_ROLE: arn:aws:iam::266302224431:role/github-shd-role
  INFRA_AWS_REGION: eu-west-3
  PROJECT_CLIENT_WORKSPACE: './src/cv-client'

jobs:
  build_iac:
    name: Build (IaC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test projects
        uses: amilochau/github-actions/build/terraform@v4

  build_client:
    name: Build (Client)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        uses: amilochau/github-actions/build/node@v4
        with:
          projectWorkspace: ${{ env.PROJECT_CLIENT_WORKSPACE }}
      - name: Upload artifact (compressed)
        uses: actions/upload-artifact@v3
        with:
          name: build-node-compressed
          path: ${{ env.PROJECT_CLIENT_WORKSPACE }}/dist
          if-no-files-found: error
          retention-days: 1

  deploy_dev:
    name: Deploy (DEV)
    needs: [build_iac, build_client]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: DEV
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact (Client)
        uses: actions/download-artifact@v3
        with:
          name: build-node-compressed
          path: ${{ env.PROJECT_CLIENT_WORKSPACE }}/dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.INFRA_AWS_ROLE }}
          aws-region: ${{ env.INFRA_AWS_REGION }}

      - name: Deploy Terraform module
        uses: amilochau/github-actions/deploy/terraform@v4
        with:
          workspaceName: ${{ env.INFRA_WORKSPACE_DEV }}

  deploy_prd:
    name: Deploy (PRD)
    if: github.ref == 'refs/heads/main'
    needs: [deploy_dev]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: PRD
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact (Client)
        uses: actions/download-artifact@v3
        with:
          name: build-node-compressed
          path: ${{ env.PROJECT_CLIENT_WORKSPACE }}/dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.INFRA_AWS_ROLE }}
          aws-region: ${{ env.INFRA_AWS_REGION }}

      - name: Deploy Terraform module
        uses: amilochau/github-actions/deploy/terraform@v4
        with:
          workspaceName: ${{ env.INFRA_WORKSPACE_PRD }}
